### PR TITLE
Enhanced task prioritization

### PR DESCRIPTION
**Pull request by clementpoiret**
This PR enhance the workflow to assign priority to a given task, by:

1. Computing a priority score,
2. Sorting according to this score,
3. Changes the behavior of the `:Dooing` command, such as:
    a. `:Dooing`: opens the buffer;
    b. `:Dooing add Task`: adds a task;
    c. `:Dooing add -p important,urgent Task`: adds a task with a given priority.

### CODE REVIEW

**Comment by clementpoiret** [comment]
Next step, but not today, I'll do another PR by including time into the sorting. Maybe also add this new overdue flag there too, so that overdue tasks are always first :)

**Comment by atiladefreitas** [comment]
hey! great work! 

in my tests it is working seamlessly with the new calendar update. 

please, I invite you to test it out @derivia.
I'm testing locally by running `git fetch origin pull/13/head:pr-13-test`

**Review by atiladefreitas — APPROVED** [review]
look good to me, great work!

**Comment by atiladefreitas** [comment]
hey @clementpoiret. 

the property `prioritization = false` still having importance? I've settled it in that first version that I've built

**Comment by clementpoiret** [comment]
Thanks! :)
Hmm, it's still being used, but yes, it can be removed. Maybe that priorities can be disabled by specifically adding `priorities = {}` in the config?

Thanks for the merge

**Pull request merged**
