### PR TITLE
Add scratchpad feature

### LINKED ISSUE #27: Feature Request: To-do notes
I like my to dos to have notes associated with them so I can keep track of progress or thoughts I have during the process of completing the task. This could be a simple description that could show in a floating window to the right, or a whole new buffer. I currently keep to dos in a markdown file with headings and bullets, but I really like your ability to mark things with urgent and important tags (along with a simple UI).

### PR DESCRIPTION
**Pull request by derivia**
This PR implements a scratchpad feature for todos, enabling users to add and edit notes associated with individual todo items.

Suggestions:
  - Render syntax highlighting based on filetype for the todo scratchpad (e.g., Markdown, LaTeX) to improve usability for users that tend to work with specific formats.

Closes #27.

### CODE REVIEW

**Comment by derivia** [comment]
[83a5878](https://github.com/atiladefreitas/dooing/pull/37/commits/83a5878a45f3f0ca53d69f1623dc906d3684c0e0) removes a dump function that i use on lua development. But you can keep that in your snippets if you want.

**Comment by derivia** [comment]
I think it would bloat the main window. Maybe an notepad icon aside would be better.

**Comment by atiladefreitas** [comment]
agree, can you add that icon?

**Comment by derivia** [comment]
I had a problem, but i'm short on time right now.
After closing the "priority window" (the one with "important" and "urgent"), after creating a todo, the <CR> keymap still tries to close it, inside any window [not only scoped to dooing-related windows/buffers]

**Comment by atiladefreitas** [comment]
I can dive into it later today

**Comment by derivia** [comment]
Feel free to merge.
You can change the default icon as well if you want, to keep things looking ASCII-like.

**Comment by atiladefreitas** [comment]
sorry for the very huge delay, I got stuck in some work

**Review by atiladefreitas — APPROVED** [review]

**Pull request merged**
