### PR TITLE
Adding import and export functionality.

### PR DESCRIPTION
**Pull request by derivia**
This PR introduces import and export features to the todo list window. 
Users are prompted with a file path for both export and import.

### CODE REVIEW

**Comment by atiladefreitas** [comment]
:0 you are on fire

**Comment by atiladefreitas** [comment]
can you please update the Readme.md with the new keys? also the help window

**Comment by derivia** [comment]
Sorry @atiladefreitas , didn't saw that. I'm going to make a PR with the proper documentation changes from my 3 others PRs. Including this one.

**Comment by derivia** [comment]
Closing since one pull request will be enough.

**Pull request closed without merging**
